FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY clients/streamlit_app.py ./clients/streamlit_app.py

EXPOSE 8501

CMD ["streamlit", "run", "clients/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]